### PR TITLE
Compatibility fixes for Babel 7

### LINKED ISSUE #209: Babel 7 Support?
I'm wondering if you have any plans to support Babel 7?

### PR DESCRIPTION
**Pull request by NilSet**
Fixed an issue where modules were interpreted as commonjs even when es6
Removed direct imports of babel-types and babel-template

Fixes #209 maybe

### CODE REVIEW

File: src/RewireState.js [hunk 1]
```diff
@@ -12,13 +12,21 @@
  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.*/
 
-import { universalAccesorsTemplate, enrichExportTemplate, filterWildcardImportTemplate } from './Templates.js';
+import Templates from './Templates.js';
 import { wasProcessed, noRewire } from './RewireHelpers.js';
-import * as t from 'babel-types';
+var t;
+var universalAccesorsTemplate;
```
Comment (ilias-t) [inline src/RewireState.js]: Why not use scope these variables to the `RewireState` class with `this.<variable>`, similar to `this.isES6Module` and the others? Also we should probably prefer `const` or `let` to `var`.

File: src/RewireState.js [hunk 2]
```diff
@@ -126,6 +134,8 @@ export default class RewireState {
 			UNIVERSAL_RESETTER_ID :this.getUniversalResetterID(),
 			UNIVERSAL_WITH_ID :this.getUniversalWithID(),
 			API_OBJECT_ID: this.getAPIObjectID(),
+			INTENTIONAL_UNDEFINED: t.identifier('INTENTIONAL_UNDEFINED'),
+			__INTENTIONAL_UNDEFINED__: '__INTENTIONAL_UNDEFINED__',
```
Comment (ilias-t) [inline src/RewireState.js]: What is this one used for?

File: src/Templates.js [hunk 3]
```diff
@@ -36,16 +35,16 @@ let API_OBJECT_ID = {};
...
-    if (value === INTENTIONAL_UNDEFINED) {
-      return undefined;
-    } else {
-      return value;
-    }
-  }
+	if (REWIRED_DATA_IDENTIFIER === undefined || REWIRED_DATA_IDENTIFIER[variableName] === undefined) {
+		return ORIGINAL_VARIABLE_ACCESSOR_IDENTIFIER(variableName);
+	} else {
+		var value = REWIRED_DATA_IDENTIFIER[variableName];
```
Comment (ilias-t) [inline src/Templates.js]: `const`?

File: src/RewireState.js (hunk 1 above)
Comment (NilSet) [reply src/RewireState.js]: I ran into issues with `this.t`, because of a few places it is referenced from unbound functions. Also it was a larger change. This way we just inject the lib at the top level when we get it from babel invoking us.

File: src/RewireState.js (hunk 2 above)
Comment (NilSet) [reply src/RewireState.js]: babel 7's template is more picky about strings that look like placeholders but are not filled in. This was the simplest way to fix it without changing the generated code.

File: src/Templates.js (hunk 3 above)
Comment (NilSet) [reply src/Templates.js]: I just fixed the tabs to be consistent.

**Comment by NilSet** [comment]
@speedskater I just noticed the `version-1.1.0` branch. Should I have based this off of that branch?

File: src/Templates.js (hunk 3 above)
Comment (damassi) [reply src/Templates.js]: All of these `vars` and so on are from original code, so should probably not be changed in this PR.

**Comment by damassi** [comment]
Can confirm this PR works in our new Babel 7 codebase

**Comment by speedskater** [comment]
@NilSet, @ilias-t, @damassi thank you all for your work on this pull request. I am currently not in the office but I will review it tomorrow in the evening. Regarding the branch, i think the current branch would indeed be version-1.1.0 branch. Neverthless I will try to merge the version 1.1.0 branch into master and than using this PR an if possible some other open PRs to create a 1.2.0 branch and based on this a 1.2.0-RC1.

Regarding the var/const/let issues I would propose to remain with the vars until we reach babel 7 support, and to tackle this in a separate branch/PR.

Is this procedure okay for you?

**Comment by damassi** [comment]
That would be fantastic, thanks @speedskater 👍

**Comment by NilSet** [comment]
I have a rebase onto 1.1.0 mostly done. I may switch to a less hacky solution for the template placeholder thing.

**Comment by NilSet** [comment]
I'll keep this pointed at master, but [compare the branch with version-1.1.0](https://github.com/speedskater/babel-plugin-rewire/compare/version-1.1.0...NilSet:babel7-compat) to see only my changes

**Comment by speedskater** [comment]
@NilSet thanks again for you PR. I have merged it into the 1.2.0 branch and puglished 1.2.0-rc.1 and  on npm as a prerelease. 
Could you all please test this release in your code bases. If I won't get any negativ feedback till next monday I will convert it to the final 1.2.0 and will then merge it onto master.
@damassi could you please test it in your babel 7 codebase ?

**Comment by speedskater** [comment]
@NilSet  I also added you as a contributor to the README. I hope this i okay with you?

**Comment by NilSet** [comment]
1.2.0-rc.1 seems to be working great!

**Comment by NilSet** [comment]
@speedskater How has the feedback been? Do we look ok to merge version-1.2.0 into master and release it as latest?

**Comment by AndrewSouthpaw** [comment]
@NilSet or anyone else, are you by chance using it in your project with Flow? There's an open issue around #208 which warns that things could start breaking in Babel 7, and I'm curious if it's actually the case. (We're not using Babel 7 so I haven't had the chance to test it out.)

**Comment by augbog** [comment]
Also curious about the progress of this? Would love to see this merged :)

**Comment by villesau** [comment]
Would love to see this merged!

**Comment by adamnoakes** [comment]
I've tried rc1 with the 7.0.0 babel release and am having an issue
```
export { _get__2 as __get__, _get__2 as __GetDependency__, _set__2 as __Rewire__, _set__2 as __set__, _reset__2 as __ResetDependency__, _RewireAPI__2 as __RewireAPI__ };
^^^^^^

SyntaxError: Unexpected token export

```

Has anyone else tried with 7.0.0?

**Comment by miguel-orange** [comment]
@adamnoakes - I've tested with babel 7, seems to be working.

**Comment by adamnoakes** [comment]
@miguel-orange i done some more investigation and it works ok for me when i use babel cli but when using babel register i get the issues, not sure if it's an issue with this, babel register or my setup. Are you using babel-register?

**Comment by kibertoad** [comment]
@speedskater Does this still need anything to be done before it can be merged to master?

**Comment by damassi** [comment]
@speedskater has unfortunately gone missing :(

**Comment by speedskater** [comment]
@kibertoad @damassi sorry for beeing not available for the project over the last month and neglecting the project. Unfortunately, I am currently changing jobs and finishing my PhD thesis at the same time. Therefore it won't get better soon. I hope I will be able to contribute some improvement in the future, but it will take some time. 
In the meantime I will add a former coworker of mine as a contributer to the project, so he will be able to provide bugfixes.
